# Generated by Django 4.0.6 on 2022-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('Parttime', 'Partime'), ('NOrmalTime', 'Normaltime'), ('OverTime', 'Overtime')], default='Partime', max_length=250),
            preserve_default=False,
        ),
    ]
